# Seed-данные справочников из текущей версии (db_manager.py)
# Формат: python-списки. Для веб-версии перенести в Alembic-миграцию.

starter_niches = [
            ("travel",         "Трэвел / путешествия",
             "Поездки, маршруты, направления, путеводители."),
            ("home",           "Дом / ремонт / быт",
             "Ремонт, материалы, обустройство, бытовые задачи."),
            ("auto",           "Авто-эксплуатация",
             "Обслуживание, ремонт, выбор, эксплуатационные вопросы."),
            ("lifestyle",      "ЗОЖ / lifestyle",
             "Здоровье, привычки, питание, физическая активность."),
            ("pets",           "Питомцы",
             "Уход, выбор, дрессировка, здоровье животных."),
            ("garden",         "Сад / дача",
             "Растения, посадка, уход, сезонные работы."),
            ("utility",        "Образовательный utilitarian-контент",
             "Инструкции к сервисам, программам, практические how-to."),
        ]

starter_archetypes = [
            # Travel
            ("travel-destination-guide",  "travel", "Путеводитель по направлению",
             "Как добраться, когда ехать, что смотреть, бюджет.",
             ["informational"]),
            ("travel-route",              "travel", "Маршрут",
             "Готовый план поездки на N дней.",
             ["informational", "how_to"]),
            ("travel-top-list",           "travel", "Топ / подборка",
             "Лучшие места, что посмотреть в X.",
             ["informational"]),
            ("travel-comparison",         "travel", "Сравнение направлений",
             "X или Y, куда поехать.",
             ["informational"]),
            ("travel-personal",           "travel", "Личный опыт",
             "Как я съездил в X, впечатления и наблюдения.",
             ["informational"]),
            ("travel-practical-guide",    "travel", "Практический гайд",
             "Как оформить, как спланировать, что подготовить.",
             ["how_to"]),

            # Home
            ("home-full-guide",           "home",   "Полное руководство",
             "Всё о X в контексте дома и ремонта.",
             ["informational"]),
            ("home-comparison",           "home",   "Сравнение материалов / решений",
             "X vs Y: цена, срок, плюсы и минусы.",
             ["informational"]),
            ("home-howto-diy",            "home",   "Пошаговая инструкция (DIY)",
             "Как сделать X своими руками.",
             ["how_to"]),
            ("home-top-choice",           "home",   "Топ / выбор",
             "Лучшие X для дома, как выбрать X.",
             ["informational"]),
            ("home-problem-solving",      "home",   "Решение проблемы",
             "Как устранить X, что делать если X.",
             ["how_to", "informational"]),

            # Auto
            ("auto-howto-service",        "auto",   "Как сделать / обслужить",
             "Пошаговое обслуживание или ремонт.",
             ["how_to"]),
            ("auto-comparison",           "auto",   "Сравнение",
             "X vs Y.",
             ["informational"]),
            ("auto-top-choice",           "auto",   "Выбор / топ",
             "Как выбрать X, лучшие X.",
             ["informational"]),
            ("auto-problem-solving",      "auto",   "Решение проблемы",
             "Что делать если X.",
             ["how_to", "informational"]),
            ("auto-full-guide",           "auto",   "Полное руководство",
             "Всё про X в контексте эксплуатации.",
             ["informational"]),

            # Lifestyle
            ("lifestyle-full-guide",      "lifestyle", "Полное руководство",
             "Всё о X для здоровья и образа жизни.",
             ["informational"]),
            ("lifestyle-howto",           "lifestyle", "How-To",
             "Как начать X, как делать X.",
             ["how_to"]),
            ("lifestyle-top-list",        "lifestyle", "Топ / подборка",
             "Лучшие X.",
             ["informational"]),
            ("lifestyle-myths",           "lifestyle", "Мифы и факты",
             "Правда о X, развенчание мифов.",
             ["informational"]),
            ("lifestyle-comparison",      "lifestyle", "Сравнение подходов",
             "X vs Y, какой подход выбрать.",
             ["informational"]),

            # Pets
            ("pets-full-guide",           "pets",   "Полное руководство",
             "Всё об уходе за X.",
             ["informational"]),
            ("pets-howto",                "pets",   "How-To",
             "Как приучить / лечить / кормить.",
             ["how_to"]),
            ("pets-choice",               "pets",   "Выбор",
             "Как выбрать X, породы, корма.",
             ["informational"]),
            ("pets-problem-solving",      "pets",   "Решение проблемы",
             "Что делать если питомец X.",
             ["how_to", "informational"]),
            ("pets-comparison",           "pets",   "Сравнение",
             "X vs Y.",
             ["informational"]),

            # Garden
            ("garden-full-guide",         "garden", "Полное руководство",
             "Всё о выращивании X.",
             ["informational"]),
            ("garden-howto",              "garden", "Пошаговая инструкция",
             "Как посадить, ухаживать.",
             ["how_to"]),
            ("garden-seasonal",           "garden", "Сезонный гайд",
             "Что делать в саду в X сезон.",
             ["informational", "how_to"]),
            ("garden-top-choice",         "garden", "Выбор / топ",
             "Лучшие сорта, инструменты.",
             ["informational"]),
            ("garden-problem-solving",    "garden", "Решение проблемы",
             "Болезни, вредители.",
             ["how_to", "informational"]),

            # Utility
            ("utility-service-guide",     "utility", "Инструкция к сервису",
             "Как пользоваться X.",
             ["how_to"]),
            ("utility-howto",             "utility", "How-To",
             "Как сделать X в сервисе или программе.",
             ["how_to"]),
            ("utility-comparison",        "utility", "Сравнение сервисов",
             "X vs Y.",
             ["informational"]),
            ("utility-problem-solving",   "utility", "Решение проблемы",
             "Как исправить ошибку X.",
             ["how_to"]),
            ("utility-full-guide",        "utility", "Полное руководство",
             "Всё о X в контексте сервиса.",
             ["informational"]),
        ]
